# Generated by Django 4.0.4 on 2023-06-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
